
export const products = [
    {
      id: 1,
      name: "Mix Berries",
      price: 200,
      category: "medium",
      image:  "/imgs/pro1.jpg",
    },
    {
      id: 2,
      name: "Pink set",
      price: 500,
      category: "large",
      image: "/imgs/pro2.jpg",
    },
    {
      id: 3,
      name: "Classic set",
      price: 100,
      category: "medium",
      image: "/imgs/pro3.jpg",
    },
    {
      id: 4,
      name: "hourglass candle",
      price: 250,
      category: "large",
      image: "/imgs/pro4.jpg",
    },
    {
      id: 5,
      name: "bubbles candle",
      price: 190,
      category: "large",
      image: "/imgs/pro5.jpg",
    },
    {
      id: 6,
      name: "jar cheese cake",
      price: 250,
      category: "medium",
      image: "/imgs/pro6.jpg",
    },
    {
      id: 7,
      name: "Candle bouquet",
      price: 300,
      category: "large",
      image: "/imgs/pro7.jpg",
    },
    {
      id: 8,
      name: "Luxury flower tray",
      price: 350,
      category: "large",
      image: "/imgs/pro8.jpg",
    },
    {
      id: 9,
      name: "Mini candle",
      price: 100,
      category: "small",
      image: "/imgs/pro9.jpg",
    },
    {
      id: 10,
      name: "Wax diffuser",
      price: 150,
      category: "medium",
      image: "/imgs/pro10.jpg",
    },
    {
      id: 11,
      name: "flower bouquet",
      price: 110,
      category: "small",
      image: "/imgs/pro11.jpg",
    },
    {
      id: 12,
      name: "victoria secret",
      price: 180,
      category: "medium",
      image: "/imgs/pro12.jpg",
    },
    {
      id: 13,
      name: "warm vanilla",
      price: 220,
      category: "large",
      image: "/imgs/pro13.jpg",
    },
    {
      id: 14,
      name: "Teddy Bear candle",
      price: 180,
      category: "medium",
      image: "/imgs/pro14.jpg",
    },
    {
      id: 15,
      name: "Sea candle",
      price: 195,
      category: "large",
      image: "/imgs/pro15.jpg",
    },
  ];